Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls', namespace='blog_app')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/urls.py
from django.urls import path
from blog_app.views import (BlogListView, BlogDetailView,CinemaListView,
                    TecnologiaListView, EsportesListView,FinancasListView,
)

app_name = 'blog_app'

urlpatterns = [ 
    path('', BlogListView.as_view(), name='blog'),
    path('detalhe/<int:pk>', BlogDetailView.as_view(), name='detalhes'),
    path('cinema/', CinemaListView.as_view(), name='cinema'),
    path('tecnologia/', TecnologiaListView.as_view(), name='tecnologia'),
    path('esportes/', EsportesListView.as_view(), name='sports'),
    path('financas/', FinancasListView.as_view(), name='financas'),
]

blog_app/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

LISTA_CATEGORIA = (
    ('esportes', 'Esportes'),
    ('cinema', 'Cinema'), 
    ('tecnologia', 'Tecnologia'),
    ('finanças', 'Finanças'),
    
)
class Blog(models.Model):
    titulo = models.CharField(max_length=1000)
    mini_descricao = models.CharField(max_length=2000)
    descricao = RichTextField(max_length=1000000)
    image = models.ImageField(upload_to='thumb_img')
    data = models.DateTimeField(auto_now_add = True)
    autor = models.CharField(max_length=30)
    categoria = models.CharField(max_length=30, choices=LISTA_CATEGORIA)

    def __str__(self):
        return self.titulo

blog_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Blog



#Blog inicial
class BlogListView(ListView):
    template_name = 'index.html'
    model = Blog
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        post_blog = Blog.objects.order_by('-data')
        context["post_blog"] = post_blog
        return context

    
#Página com somente conteudo relacionados ao cinema
class CinemaListView(ListView):
    template_name = 'cinema.html'
    model = Blog
    paginate_by = 10
    

    def get_context_data(self, **kwargs):
        context = super(CinemaListView, self).get_context_data(**kwargs)
        categoria_cinema = Blog.objects.filter(categoria='cinema').order_by('-data')
        context['categoria_cinema'] = categoria_cinema
        return context



# Página com  conteudos relacionados a tecnologia e jogos
class TecnologiaListView(ListView):
    template_name = 'tecnologia_jogos.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(TecnologiaListView, self).get_context_data(**kwargs)
        categoria_tecnologia = Blog.objects.filter(categoria='tecnologia').order_by('-data')
        context['categoria_tecnologia'] = categoria_tecnologia
        return context


# Página Relacionados a conteudos de Esportes
class EsportesListView(ListView):
    template_name = 'esportes.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(EsportesListView, self).get_context_data(**kwargs)
        categoria_esportes = Blog.objects.filter(categoria='esportes').order_by('-data')
        context['categoria_esportes'] = categoria_esportes
        return context


# Página relacionado a Financia
class FinancasListView(ListView):
    template_name = 'financas.html'
    model = Blog

    def get_context_data(self, **kwargs):
        context = super(FinancasListView, self).get_context_data(**kwargs)
        categoria_financas = Blog.objects.filter(categoria='finanças').order_by('-data')
        context['categoria_financas'] = categoria_financas
        return context



# Página de Detalhes dos posts
class BlogDetailView(DetailView):
    template_name = 'detalhes.html'
    model = Blog

templates/cinema.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Blog - Hiago Souza - Cinema</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/blog/">

    

    

<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header class="site-header py-1">
    <div>
      <a href="/"><img src="{% static 'img/logo-blog.png' %}" style="width:100%; height:300px;"></a>
    </div>
  </header>


  <div class="site-header py-1 mb-2">
    <nav class="container d-flex flex-column flex-md-row justify-content-between">
      <a class="py-2" href="{% url 'blog_app:blog' %}">Início</a>
      <a class="py-2" href="{% url 'blog_app:sports' %}">Esportes</a>
      <a class="py-2" href="{% url 'blog_app:cinema' %}">Cinema</a>
      <a class="py-2" href="{% url 'blog_app:tecnologia' %}">Tecnologia</a>
      <a class="py-2" href="{% url 'blog_app:financas' %}">Finanças</a>
    </nav>
    <hr>
  </div>

<main class="container">

 

  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        Noticías sobre Cinema
      </h3>

      {% for cinema in categoria_cinema %}
      <article class="blog-post">
        <h2 class="blog-post-title mb-1">{{ cinema.titulo }}</h2>
        <p class="blog-post-meta">Por: <strong>{{ cinema.autor }}</strong>. há {{ cinema.data|timesince }} atrás.</p>

        <img src="{{ cinema.image.url }}" class="img-fluid" width="500" height="250">
        <br><br>
        <p class="fs-5">{{ cinema.mini_descricao }}</p>
        <a href="{% url 'blog_app:detalhes' cinema.id %}">Continuar Lendo...</a>
        <hr>
        
        {% endfor %}

      <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo;Primeira</a></li>
          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
        {% endif %}

        <li class="page-item">
          <span class="page-link">Página: {{page_obj.number}}</span>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page.number }}">Próximo</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.number_pages }}">Última&raquo;</a></li>
        {% endif %}
      </ul>    

      </article>
    </div>

                        <!--Aside Bar-->

    <div class="col-md-4">
      <h4 class="fst-italic text-center">Apoio:</h4>
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-light rounded">                   
          <a href="https://www.instagram.com/spacegames_imports/" target="_blank"><img src="{% static 'img/logo-space-games.jpg'%}" class="img-fluid" width="300" height="250"></a>
        </div>
                                        
        <div class="p-4 mb-3 bg-light rounded">              
          <a href="https://www.instagram.com/agilitytelecom_areiabranca/" target="_blank"><img src="{% static 'img/logo-agility.jpg'%}" class="img-fluid" width="300" height="250"></a>
        </div>

        <div class="p-4 mb-3 bg-dark rounded">
          <a href="https://www.instagram.com/clinauto.auto/" target="_blank"><img src="{% static 'img/logo-anchieta.png'%}" class="img-fluid" width="300" height="250"></a>
        </div>

       

        <div class="p-4">
          <h4 class="fst-italic">Contato</h4>
          <ol class="list-unstyled">
            <li><a href="https://www.facebook.com/hiaguinhospencer" target="_blank">Facebook</a></li>
            <li><a href="https://www.instagram.com/hiaguinhospencer/" target="_blank">Instagram</a></li>
            <li><a href="https://wa.me/5584988638467" target="_blank">Whatsapp</a></li>
          </ol>
        </div>
      </div>
    </div>
  </div>



</main>

<footer class="blog-footer">
  <p>Criado por <strong>Hiago Souza</strong></p>
  <p>
    <a href="#">Voltar pro topo.</a>
  </p>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>

templates/esportes.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Blog - Hiago Souza - Esportes</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/blog/">

    

    

<link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
  </head>
  <body>
    
<div class="container">
  <header class="site-header py-1">
    <div>
      <a href="/"><img src="{% static 'img/logo-blog.png' %}" style="width:100%; height:300px;"></a>
    </div>
  </header>


  <div class="site-header py-1 mb-2">
    <nav class="container d-flex flex-column flex-md-row justify-content-between">
      <a class="py-2" href="{% url 'blog_app:blog' %}">Início</a>
      <a class="py-2" href="{% url 'blog_app:sports' %}">Esportes</a>
      <a class="py-2" href="{% url 'blog_app:cinema' %}">Cinema</a>
      <a class="py-2" href="{% url 'blog_app:tecnologia' %}">Tecnologia</a>
      <a class="py-2" href="{% url 'blog_app:financas' %}">Finanças</a>
    </nav>
    <hr>
  </div>

<main class="container">

 

  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        Noticías sobre Esportes
      </h3>

      {% for esportes in categoria_esportes %}
      <article class="blog-post">
        <h2 class="blog-post-title mb-1">{{ esportes.titulo }}</h2>
        <p class="blog-post-meta">Por: <strong>{{ esportes.autor }}</strong>. há {{ esportes.data|timesince }} atrás.</p>

        <img src="{{ esportes.image.url }}" class="img-fluid" width="500" height="250">
        <br><br>
        <p class="fs-5">{{ esportes.mini_descricao }}</p>
        <a href="{% url 'blog_app:detalhes' esportes.id %}">Continuar Lendo...</a>
        <hr>
        
        {% endfor %}

      <ul class="pagination justify-content-center">

        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">&laquo;Primeira</a></li>
          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
        {% endif %}

        <li class="page-item">
          <span class="page-link">Página: {{page_obj.number}}</span>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page.number }}">Próximo</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.number_pages }}">Última&raquo;</a></li>
        {% endif %}
      </ul>    

      </article>
    </div>

                        <!--Aside Bar-->

          <div class="col-md-4">
            <h4 class="fst-italic text-center">Apoio:</h4>
          <div class="position-sticky" style="top: 2rem;">
          <div class="p-4 mb-3 bg-light rounded">                   
            <a href="https://www.instagram.com/spacegames_imports/" target="_blank"><img src="{% static 'img/logo-space-games.jpg'%}" class="img-fluid" width="300" height="250"></a>
          </div>
                                                            
          <div class="p-4 mb-3 bg-light rounded">              
            <a href="https://www.instagram.com/agilitytelecom_areiabranca/" target="_blank"><img src="{% static 'img/logo-agility.jpg'%}" class="img-fluid" width="300" height="250"></a>
          </div>
                    
          <div class="p-4 mb-3 bg-dark rounded">
            <a href="https://www.instagram.com/clinauto.auto/" target="_blank"><img src="{% static 'img/logo-anchieta.png'%}" class="img-fluid" width="300" height="250"></a>
          </div>


        <div class="p-4">
          <h4 class="fst-italic">Contato</h4>
          <ol class="list-unstyled">
            <li><a href="https://www.facebook.com/hiaguinhospencer" target="_blank">Facebook</a></li>
            <li><a href="https://www.instagram.com/hiaguinhospencer/" target="_blank">Instagram</a></li>
            <li><a href="https://wa.me/5584988638467" target="_blank">Whatsapp</a></li>
          </ol> 
        </div>
      </div>
    </div>
  </div>



</main>

<footer class="blog-footer">
  <p>Criado por <strong>Hiago Souza</strong></p>
  <p>
    <a href="#">Voltar pro topo.</a>
  </p>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </body>
</html>